steps:

- id: "Copy robots.txt file"
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', "gs://analytics_recipe-box-box-config/robots.txt", "./public/"]

- id: "Copy sitemap.xml file"
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', "gs://analytics_recipe-box-box-config/sitemap.xml", "./public/"]

- id: "Copy script Firebase"
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', "gs://firebase_recipe-box-config/conf-firebase.js", "./src/"]

- id: "install dependency"
  name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- id: "build static files"
  name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']

- id: "Sync static files in bucket"
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-d', '-r', './build/', 'gs://website_recipe-box-builded/']

- id: "Download git repo for config App Engine"
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://source.developers.google.com/p/recipe-box-236817/r/Config-App-Engine-Recipe-Box']
  
- id: "DEPLOY ON APP ENGINE"
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', '--config', './Config-App-Engine-Recipe-Box/master/cloudbuildDeploy.yaml', './Config-App-Engine-Recipe-Box/']